#pragma once

#define LINES_CLI_VERSION_STR "0.1.1a"
#define LINES_CLI_VERSION 000101
#define LINES_CLI_VERSION_MAJOR 0
#define LINES_CLI_VERSION_MINOR 1
#define LINES_CLI_VERSION_PATCH 1
#define LINES_CLI_VERSION_BETA 0
#define LINES_CLI_VERSION_ALPHA 1
