name: Build

on:
  push:
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Conan
        run: pip install conan --break-system-packages

      - name: Cache Conan
        uses: actions/cache@v5
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ runner.arch }}-

      - name: Detect profile
        run: conan profile detect --force

      - name: Build
        run: make BUILD_TYPE=Test

      - name: Test
        run: make test

  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Conan
        run: pip install conan --break-system-packages

      - name: Cache Conan
        uses: actions/cache@v5
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ runner.arch }}-

      - name: Detect profile
        run: conan profile detect --force

      - name: Build
        run: make BUILD_TYPE=Test

      - name: Test
        run: make test

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Conan
        run: pip install conan --break-system-packages

      - name: Cache Conan
        uses: actions/cache@v5
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ runner.arch }}-

      - name: Detect profile
        run: conan profile detect --force

      - name: Build
        run: make BUILD_TYPE=Test

      - name: Test
        run: make test
